name: none-shall-pass
description: Run validations against hyperlinks in all markdown files (including Wiki pages)
inputs:
  debug:
    description: Debug flag
    required: false
    default: "false"
  owner:
    description: Owner/Organization of the repository
    required: false
    default: ${{ github.repository_owner }}
  repo:
    description: Name of the repository
    required: false
    default: ${{ github.event.repository.name }}
  excludeHostnames:
    description: Hostnames for which the failure should be ignored
    required: false
    default: ""
  failOnError:
    description: Fail the action if any hyperlinks are broken
    required: false
    default: "false"
outputs: { }
runs:
  using: composite
  steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Download Asset
      run: |
        response=$(curl -sL "https://api.github.com/repos/thevickypedia/none-shall-pass-rustic/releases/tags/v0.1.7")
        release_id=$(echo "$response" | jq -r '.id')
        tag_name=$(echo "$response" | jq -r '.tag_name')
        published_at=$(echo "$response" | jq -r '.published_at')
        asset_id=$(echo "$response" | jq -r '.assets[0].id')
        echo "'none-shall-pass-rustic' $tag_name published at $published_at"
        echo "Latest Release ID: $release_id"
        echo "Asset ID: $asset_id"
        download_url=$(echo "$response" | jq -r '.assets[0].browser_download_url')
        curl -o asset -LH "Accept: application/octet-stream" "$download_url"
        chmod +x asset
      shell: bash

    - name: Set Debug Flag
      run: |
        if [ "${{ inputs.debug }}" == "true" ] || [ "${{ env.RUNNER_DEBUG }}" == "1" ]; then
          echo "debug=true" >> $GITHUB_ENV
        else
          echo "debug=false" >> $GITHUB_ENV
        fi
      shell: bash

    - name: Run Asset
      run: |
        ./asset --debug ${{ env.debug }} --owner ${{ inputs.owner }} --repo ${{ inputs.repo }} --exclude "${{ inputs.excludeHostnames }}"
      shell: bash

    - name: Summary
      run: |
        if [ -f "GH_ACTIONS_SUMMARY" ]; then
          echo "::error title=Failed hyperlinks::Following hyperlinks are broken."
          while IFS= read -r line || [[ -n "$line" ]]; do
            echo "$line" >> $GITHUB_STEP_SUMMARY
          done < "GH_ACTIONS_SUMMARY"
        else
          echo "::notice title=Successful Run::No broken hyperlinks found."
        fi
      shell: bash

    - name: Exit Code
      if: inputs.failOnError == 'true'
      run: |
        if [ -f "GH_ACTIONS_SUMMARY" ]; then
          exit 1
        else
          exit 0
        fi
      shell: bash

branding:
  icon: check-square
  color: gray-dark
