name: 'none-shall-pass'
description: 'Run validations against hyperlinks in all markdown files (including Wiki pages)'
inputs:
  owner:
    description: "Owner/Organization of the repository"
    required: true
  repo:
    description: "Name of the repository"
    required: true
  fail:
    description: "Flag to fail"
    required: false
    default: "true"
  debug:
    description: "Debug flag"
    required: false
    default: "false"
outputs: {}
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.owner }}
    - ${{ inputs.repo }}
    - ${{ inputs.fail }}
    - ${{ inputs.debug }}
branding:
  icon: check-square
  color: gray-dark
